FT minting
Mintbase/mintbase-js pull request #500
Opened 2024-03-28 13:32 UTC by tifrel

2024-04-01 12:59 UTC, rubenmarcus requested changes
tests must pass

2024-04-01 13:04 UTC, rubenmarcus requested changes

2024-04-01 13:04 UTC, rubenmarcus commented on packages/sdk/src/mintOnMetadata/mintOnMetadata.ts
> +// TODO:
is this comment still needed?

2024-04-03 12:34 UTC, rubenmarcus approved these changes

2024-04-03 12:36 UTC, merged

2024-04-03 13:06 UTC, sainthiago approved these changes