Upgrade NearApiJS to v4
Mintbase/mintbase-js pull request #518
Opened 2024-07-03 10:55 UTC by bh2smith

There was only one snag in the way we convert wallet-selector.Action into nearApiJs.Action where we were previously relying on the wallet-selector to do the conversion (it is outdated) but nearApiJs has a supportive constructor.

2024-07-03 17:14 UTC, bh2smith commented on .github/workflows/branch-publish.yml
> +          npm install --frozen-lockfile
```suggestion
          npm ci
```

2024-07-03 17:39 UTC, tifrel requested changes

2024-07-03 17:39 UTC, tifrel commented on packages/auth/src/index.ts
> -export { FinalExecutionOutcome } from '@near-wallet-selector/core';
Below, njs.FEO has been exchanged for nws.FEO. Why is it the other way around here?

2024-07-03 17:39 UTC, tifrel commented on packages/sdk/src/execute/execute.utils.ts
> +          gas: BigInt(call.gas.toString()),
Shouldn't `call.gas` be a string or Bigint already?

2024-07-03 17:39 UTC, tifrel commented on packages/sdk/src/types.ts
> +export type FinalExecutionOutcome = providers.FinalExecutionOutcome;
Here moving from nws to naj again?

2024-07-03 17:39 UTC, tifrel commented on packages/sdk/src/execute/execute.utils.ts
> +          gas: BigInt(call.gas.toString()),
Also, shouldn't this be totally fine with taking a string instead of casting to BigInt again? Pretty sure it's sent to RPC as a string.

2024-07-03 20:17 UTC, bh2smith reviewed
Thanks for your eyes @tifrel - I have now explicitly labeled places where we use the NWS execution outcome. 

These two types are coming from @near-js (which is a dependency of @near-api-js) which is older on the wallet-selector because its stuck back at `near-api-js` v2.

This is the OLD TYPE:
<img width="799" alt="Screenshot 2024-07-03 at 22 08 22" src="https://github.com/Mintbase/mintbase-js/assets/11778116/4ba02a09-03ac-4bc1-84fb-bd38b0932903">

This is the NEW Type:

<img width="903" alt="Screenshot 2024-07-03 at 22 09 34" src="https://github.com/Mintbase/mintbase-js/assets/11778116/e68b2e90-9315-4b68-8aac-1c0df2e4310f">

I would love to just "cast" the data as the new type in all places that are user facing and expect it the missing field to be there (since RPCs have likely been updated to include them anyway). The we wouldn't be leaking the old type anywhere in a user facing interface and can essentially phase out the old type.

What do you think.

2024-07-03 20:17 UTC, bh2smith commented on packages/auth/src/index.ts
> -export { FinalExecutionOutcome } from '@near-wallet-selector/core';
I would argue that is it not the other way around here. It is the same way around. That is, in both cases we export from `near-api-js`.

In any case, it seems that we have to maintain their version of this type until they update the near-api on their end. A least in a couple of places. Perhaps in the places where it is still being used, I can give it a different name, but I don't understand why you think here is "the other way around" - maybe take another look at that.

2024-07-03 20:17 UTC, bh2smith commented on packages/sdk/src/execute/execute.utils.ts
> +          gas: BigInt(call.gas.toString()),
Perhaps the issue here is that we are still using the "Old Type". Will check.

> Also, shouldn't this be totally fine with taking a string instead of casting to BigInt again? 

I was just following the compiler errors.

> Shouldn't call.gas be a string or Bigint already?

call.gas here is of type `string | BN` and it is expected to be `bigint`. However, we do own this type `ContractCall` we could change it at the source.

<img width="378" alt="Screenshot 2024-07-03 at 21 46 14" src="https://github.com/Mintbase/mintbase-js/assets/11778116/7814c631-ba8b-489c-a9aa-4023cb960714">

2024-07-03 20:17 UTC, bh2smith commented on packages/sdk/src/types.ts
> +export type FinalExecutionOutcome = providers.FinalExecutionOutcome;
I was just trying to only use the one type everywhere. Realistically, I don't know why we are re-exporting this type. Is it intended that users of this package wouldn't also depend on near-api or wallet-selector?

2024-08-20 09:50 UTC, bh2smith commented
Closed in favour of #532

2024-08-20 09:50 UTC, closed without merging